package me.tr.serializer.processes.options;

public enum Options {

    // PROCESS OPTIONS
    DEFAULT_INSTANCES,
    ACCEPT_NULLS,
    ACCEPT_EMPTY_OPTIONAL,
    USE_NUMERIC_BOOLEAN,
    USE_NUMERIC_CHARACTER,
    EXCLUDE_TRANSIENT_FIELDS,
    BLOCKED_PACKAGES,
    USE_CACHE,
    IGNORE_STATIC,
    IGNORE_FINAL,
    USE_HANDLERS,
    TYPE_ALTERNATIVES,


    // DESERIALIZER OPTIONS
    IGNORE_CASE,
    ALIASES,
    DES_END_METHODS,

    // SERIALIZER OPTIONS
    SER_END_METHODS,
    MAP_ALIASES,

}
